# Generated by Django 4.0.6 on 2022-07-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='end_time_t',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_time_t',
            field=models.IntegerField(default=34),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='type',
            field=models.IntegerField(),
        ),
    ]
