# Generated by Django 4.0.6 on 2022-07-11 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_appointment_end_time_t_appointment_start_time_t_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='end_time_t',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_time_t',
        ),
    ]
